FROM ft-rails:on-build

EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

##
##	Build:
##    	docker build -t ft-rails:on-build ./ft-rails
##   	docker build -t wseegers/ex02 .
##
##	Docker run:
##		docker run -p 3000:3000 -i -d ex02
##
