FROM ft-rails:on-build

EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

#docker build -t ft-rails:on-build ./ft-rails
#git clone https://github.com/railstutorial/sample_app_rails_4.git app
#docker build -t wseegers/ex02 .
#docker run -p 3000:3000 -i -d ex02
